# Generated by Django 4.2 on 2023-04-17 12:35

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("transactions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="amount",
            name="email",
            field=models.EmailField(default="ignore_fields", max_length=100),
        ),
        migrations.AddField(
            model_name="amount",
            name="primarycurrency",
            field=models.CharField(default="gbp", max_length=100),
        ),
        migrations.AddField(
            model_name="moneytransfer",
            name="date",
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name="moneytransfer",
            name="status",
            field=models.CharField(
                choices=[
                    ("sent", "Sent"),
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("rejected", "Rejected"),
                    ("canceled", "Canceled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="amount",
            name="amount",
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
        migrations.AlterField(
            model_name="moneytransfer",
            name="enter_amount_to_transfer",
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
        migrations.AlterField(
            model_name="moneytransfer",
            name="enter_payee_email_address",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payee_money_transfers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="moneytransfer",
            name="enter_your_email_address",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="your_money_transfers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
