# Generated by Django 4.2 on 2023-04-17 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0002_amount_email_amount_primarycurrency_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="moneytransfer",
            name="payee_currency",
            field=models.CharField(default="gbp", max_length=100),
        ),
        migrations.AddField(
            model_name="moneytransfer",
            name="payer_currency",
            field=models.CharField(default="gbp", max_length=100),
        ),
        migrations.AlterField(
            model_name="moneytransfer",
            name="enter_payee_email_address",
            field=models.EmailField(default="your_email", max_length=100),
        ),
        migrations.AlterField(
            model_name="moneytransfer",
            name="enter_your_email_address",
            field=models.EmailField(default="your_email", max_length=100),
        ),
    ]
