# Generated by Django 5.0.4 on 2024-05-03 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_moneytransfer_request_id_alter_moneytransfer_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moneytransfer',
            name='status',
            field=models.CharField(choices=[('sent', 'Sent'), ('owed', 'Owed'), ('paid', 'Paid'), ('received', 'Received'), ('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('canceled', 'Canceled'), ('declined', 'Declined')], default='pending', max_length=20),
        ),
    ]
